spring.application.name=phonebook

spring.datasource.url=${Phonebook_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${Phonebook_DB_USERNAME}
spring.datasource.password=${Phonebook_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

security.rememberme.key=${Phonebook_security_jwt_secret}